/** Test fixtures. Excluded from the build; used by the unit tests only. */
import type { EnrichedProduct, Requirement } from '../types.js';

const BASE_PRODUCT: EnrichedProduct = {
  order_number: '0000001',
  type_code: 'TEST-1',
  family: 'TEST',
  subfamily: null,
  row_type: 'product',
  category: 'Fotocelulas (Photoelectric sensors)',
  section: 'B',
  source_page: 'B-1',
  product_url: null,
  product_name: 'Test sensor',
  short_description: null,
  solution_class: 'photoelectric',
  is_safety_product: false,
  sensing_mode: 'diffuse',
  measurand: null,
  sensing_range_min_mm: null,
  sensing_range_max_mm: null,
  switching_output: null,
  output_function: null,
  connection: null,
  enclosure_rating: null,
  housing_material: null,
  operating_temp_min_c: null,
  operating_temp_max_c: null,
  process_temp_min_c: null,
  process_temp_max_c: null,
  resolution_value: null,
  resolution_unit: null,
  interface: null,
  response_time_ms: null,
  supply_voltage_min_v: null,
  supply_voltage_max_v: null,
  sensor_principle: null,
  detection_principle: null,
  light_type: null,
  scope_of_delivery: null,
  ip_ingress: null,
  ip_water: null,
  washdown_capable: null,
  mounting_type: null,
  housing_form: null,
  process_connection: null,
  probe_length_mm: null,
  process_pressure_raw: null,
  measuring_range_raw: null,
  protective_field_height_mm: null,
  safety_resolution_mm: null,
  beam_count: null,
  output_signal: null,
  fork_width_mm: null,
  fork_depth_mm: null,
  reading_window_raw: null,
  focus: null,
  shaft_diameter_raw: null,
  seal_material: null,
  protocols: [],
  search_blob: 'test sensor',
  other_specs: {},
  derived_from: {},
  low_confidence: [],
  accessory_order_numbers: [],
};

export function makeProduct(overrides: Partial<EnrichedProduct> = {}): EnrichedProduct {
  return { ...BASE_PRODUCT, ...overrides };
}

const BASE_REQUIREMENT: Requirement = {
  restated_problem: 'test problem',
  language: 'en',
  industry: null,
  application: null,
  inferred_needs: [],
  solution_classes: [],
  preferred_sensing_modes: [],
  discouraged_sensing_modes: [],
  target_distance_mm: null,
  required_protective_field_height_mm: null,
  required_safety_resolution_mm: null,
  min_ip_ingress: null,
  min_ip_water: null,
  washdown_required: false,
  min_ambient_temp_c: null,
  max_ambient_temp_c: null,
  required_protocols: [],
  required_switching_output: null,
  max_response_time_ms: null,
  keywords: [],
  budget: null,
  safety_related: false,
};

export function makeRequirement(overrides: Partial<Requirement> = {}): Requirement {
  return { ...BASE_REQUIREMENT, ...overrides };
}
